# -*- coding: utf-8 -*-
"""denoising.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p_NBq2fgAaF6300-uGYOPlYT6cCgt4QW
"""

import os
import h5py
import random
from scipy.signal import hilbert, cheby1, filtfilt
from scipy import signal
import numpy as np

"""My denosing process"""
def mydenoising(data, sampling_freq, highpass_freq, notch_freq):
    [bl, al] = signal.butter(1, (highpass_freq * 2) / sampling_freq, 'low')
    [wl, hlp] = signal.freqz(bl, al)
    Signal_lp = signal.filtfilt(bl, al, data)
    quality_factor = 20
    [bn, an] = signal.iirnotch(notch_freq, quality_factor, sampling_freq)
    [fn, hnf] = signal.freqz(bn, an)
    Signal_nf = signal.filtfilt(bn, an, Signal_lp)
    Wp = 1.4 * 2 / sampling_freq
    Ws = 0.6 * 2 / sampling_freq
    devel = 0.005
    Rp = 20 * np.log10((1 + devel) / (1 - devel))
    Rs = 20
    [N, Wn] = signal.ellipord(Wp, Ws, Rp, Rs)
    [be, ae] = signal.ellip(N, Rp, Rs, Wn, 'high')
    [fellip, hellip] = signal.freqz(be, ae, len(Signal_nf))
    Signal_ellip = signal.filtfilt(be, ae, Signal_nf)

    return Signal_ellip

"Get the sample data from DataBase 2"
data_path = '/Users/24IshaK/Desktop/UCSC Internship/records'
folder = os.listdir(data_path)
N = 10
print(f'The {N}-th record is records/A{N:05d}.h5')
data_path = '/Users/24IshaK/Desktop/UCSC Internship/records'
folder = os.listdir(data_path)

with h5py.File(f'records/A{N:05d}.h5', 'r') as f:
    ecg_signal_test = f['ecg'][()]
    print('The size of record: {}'.format(ecg_signal_test.shape))
sampling_frequency2 = 500

"read all ECG signal---lead II"
# read an ECG signal
# def read_all_data(listdir):
record_list = []
record_lists = []
Ecg_signal_random = []
Ecg_signal = []
for i_n in folder:
    res = i_n.split('.h5')[0]
    record_lists.append(res)
    record_lists.sort()
    record_list = record_lists[1:]
for N in range(len(record_list)):
    No = record_list[N]
    with h5py.File(f'records/{No}.h5','r') as f:
        ecg_signal = f['ecg'][()]
        print('No.'+ No + ' is finished')
        # plot the signal
        s = ecg_signal[2]
        s_denoised = mydenoising(s, sampling_freq=500, highpass_freq= 45, notch_freq= 50)
        "Lead II"
        "The sampling frequency is 500 Hz. L is the number of samples and 12 is the number of leads. The order of leads is I, II, III, aVR,aVL, aVF, V1, V2, V3, V4, V5, V6. There are 25770 ECG data files in total."
    Ecg_signal.append(s_denoised)
    Ecg_signal_random = random.choices(Ecg_signal, k=10)